
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package com.aidanogrady.qgrady.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int RANGE = 7;
  public static final int OUTPUT = 6;
  public static final int NUMBER = 9;
  public static final int VARIABLE = 10;
  public static final int EOF = 0;
  public static final int INPUT = 5;
  public static final int ARROW = 2;
  public static final int error = 1;
  public static final int COMMA = 3;
  public static final int SEMICOLON = 8;
  public static final int EQUALS = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ARROW",
  "COMMA",
  "EQUALS",
  "INPUT",
  "OUTPUT",
  "RANGE",
  "SEMICOLON",
  "NUMBER",
  "VARIABLE"
  };
}

