package com.aidanogrady.qgrady;

/* Simple +/-/* expression language; parser evaluates constant expressions on the fly*/
import java_cup.runtime.*;

parser code {:
    // Connect this parser to a scanner!
    scanner s;
    Parser(scanner s){ this.s=s; }
:}

/* define how to connect to the scanner! */
init with {: s.init(); :};
scan with {: return s.next_token(); :};

/* Terminals (tokens returned by the scanner). */
terminal        SEMI, COMMA, LBRACKET, RBRACKET;
terminal Double NUMBER;        // our scanner provides numbers as integers

/* Non terminals */
non terminal            box, list, row;


/* The grammar rules */
box  ::= LBRACKET list:e RBRACKET
;

list ::= row:r SEMI
       | row:r SEMI list:l
;

row  ::= NUMBER:n
       | NUMBER:n COMMA row:r
;