
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package com.aidanogrady.qgrady;

/** CUP generated interface containing symbol constants. */
public interface Sym {
  /* terminals */
  public static final int COMMA = 3;
  public static final int SEMICOLON = 2;
  public static final int error = 1;
  public static final int NUMBER = 6;
  public static final int RBRACKET = 5;
  public static final int LBRACKET = 4;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMICOLON",
  "COMMA",
  "LBRACKET",
  "RBRACKET",
  "NUMBER"
  };
}

